# Praktikum Pertemuan 3 — Menyiapkan Data Proyek agar Layak dan Aman Dianalisis

**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 3  
**Fase PjBL:** Perencanaan  
**Sub-CPMK3:** Mahasiswa mampu merumuskan pertanyaan analisis dari masalah nyata serta memperoleh data
sesuai lisensi sumbernya, serta mengidentifikasi dan menangani data pribadi yang terkandung di dalamnya (C4, A3).

**Cara kerja.** Sel bertanda `# TODO` Anda kerjakan sendiri; setiap TODO disertai *expected output* agar Anda bisa memeriksa jawaban sendiri. Sel Markdown bertanda **Jawaban Anda** diisi dengan tulisan, bukan kode.

**Bagian A–F** dikerjakan di kelas dengan dataset latihan. **Bagian G** dikerjakan bersama tim di luar kelas dengan dataset proyek Anda sendiri, dan hasilnya menjadi isi **M1 (bobot 5%)** yang dikumpulkan sesuai tenggat di LMS.

## Bagian 0 — Persiapan

Dataset latihan: **`peserta_pelatihan_umkm_2025.csv`** — 620 baris, 28 kolom.
Data pendaftaran dan hasil pelatihan UMKM binaan kampus.

> **Catatan penting:** seluruh isi dataset ini **sintetis** dan dibuat untuk latihan. Tidak ada orang nyata di dalamnya.
> Nomor NIK, nomor telepon, dan surel sengaja dibuat dengan pola yang tidak valid. Perlakukan tetap seolah-olah data nyata,
> karena itulah kebiasaan yang sedang kita latih.

In [54]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)
print('pandas', pd.__version__)

pandas 2.2.3

In [55]:
FILE = 'peserta_pelatihan_umkm_2025.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih peserta_pelatihan_umkm_2025.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')

df = pd.read_csv(FILE)
print(df.shape)
df.head(3)

(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

---
## Bagian A — Merumuskan pertanyaan analisis

Sebuah pertanyaan analisis dianggap layak bila lolos **tiga uji**:

1. **Uji kolom** — kolom mana yang akan menjawabnya?
2. **Uji bentuk jawaban** — jawabannya berupa angka, peringkat, perbandingan, atau sebaran?
3. **Uji tindak lanjut** — kalau terjawab, apa yang bisa diputuskan?

In [56]:
# TODO A1 — kenali kolom yang tersedia sebelum menulis pertanyaan
# a. Cetak daftar nama kolom beserta tipe datanya
# b. Cetak jumlah baris dan kolom
# Expected: 620 baris x 28 kolom

# a. Cetak daftar nama kolom beserta tipe datanya
print(df.dtypes)
print("-" * 40)

# b. Cetak jumlah baris dan kolom
print(f"Jumlah baris dan kolom: {df.shape[0]} baris x {df.shape[1]} kolom")

id_peserta                      object
nama_lengkap                    object
nik_dummy                        int64
no_hp                          float64
email                           object
alamat_jalan                    object
kelurahan                       object
kecamatan                       object
kota                            object
tanggal_lahir                   object
jenis_kelamin                   object
pendidikan_terakhir             object
status_disabilitas              object
jumlah_anak                      int64
penghasilan_pribadi_bulanan      int64
nama_usaha                      object
kategori_usaha                  object
produk_utama                    object
lama_usaha_tahun               float64
jumlah_karyawan                  int64
omzet_usaha_bulanan              int64
pernah_ikut_pelatihan           object
kanal_pendaftaran               object
tanggal_daftar                  object
kehadiran_persen                 int64
skor_prates                      int64
skor_pascates                  float64
tingkat_kepuasan               float64
dtype: object
----------------------------------------
Jumlah baris dan kolom: 620 baris x 28 kolom

### TODO A2 — perbaiki tiga pertanyaan berikut

Tulis versi perbaikannya di sel di bawah, beserta kolom yang akan dipakai.

| No | Draf pertanyaan | Masalahnya |
|---|---|---|
| 1 | Bagaimana kondisi peserta pelatihan? | Terlalu kabur |
| 2 | Apakah peserta yang lebih kaya lebih sukses? | "Kaya" dan "sukses" belum didefinisikan sebagai kolom |
| 3 | Apakah pelatihan menaikkan omzet peserta? | Uji kolom gagal — cek sendiri mengapa |

**Jawaban Anda:**

1. Perbaikan: Bagaimana sebaran tingkat pendidikan terakhir dari peserta pelatihan? — Kolom: `pendidikan_terakhir`
2. Perbaikan: Apakah peserta dengan omzet usaha bulanan yang lebih tinggi cenderung memiliki jumlah karyawan yang lebih banyak? — Kolom: `omzet_usaha_bulanan`, `jumlah_karyawan`
3. Mengapa uji kolom gagal: Karena dataset ini hanya mengukur kondisi usaha peserta (yaitu `omzet_usaha_bulanan` saat mendaftar) sebelum/selama program pelatihan berlangsung, dan tidak memiliki kolom data omzet usaha setelah mereka menyelesaikan pelatihan untuk dibandingkan.

In [57]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar

kolom_omzet = [col for col in df.columns if 'omzet' in col]
print("Kolom yang mengandung kata 'omzet':", kolom_omzet)

Kolom yang mengandung kata 'omzet': ['omzet_usaha_bulanan']

---
## Bagian B — Skala pengukuran

### TODO B1 — klasifikasikan delapan kolom berikut

Isi tabel di sel Markdown ini. Pilihan: **nominal · ordinal · interval · rasio**.

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` | nominal | Data kategori tanpa urutan alami (misal: Kuliner, Jasa Digital) |
| `pendidikan_terakhir` | ordinal | Kategori yang memiliki tingkatan atau jenjang yang jelas (SD < SMP < SMA < D3 ...) |
| `skor_prates` | interval | Nilai numerik tanpa nol mutlak (skor 0 bukan berarti tidak memiliki pengetahuan sama sekali) |
| `omzet_usaha_bulanan` | rasio | Nilai numerik dengan nol mutlak (omzet 0 berarti tidak ada pemasukan sama sekali) |
| `jumlah_karyawan` | rasio | Nilai numerik berupa hasil perhitungan dengan nol mutlak (0 berarti tidak memiliki karyawan) |
| `tingkat_kepuasan` | ordinal | Data penilaian berskala (skala kepuasan 1-5 memiliki urutan tingkat kepuasan) |
| `tanggal_daftar` | interval | Nilai penanggalan yang tidak memiliki nilai nol mutlak |
| `kecamatan` | nominal | Data kategori nama daerah/lokasi tanpa urutan tertentu |

In [58]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe
# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
#    Urutan: SD < SMP < SMA/SMK < D3 < S1 < S2
# b. Tampilkan value_counts() yang sudah urut menurut jenjang (bukan abjad)
# c. Cetak median jenjang pendidikan lewat .cat.codes
# Expected: median = SMA/SMK

# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
urutan_pendidikan = ['SD', 'SMP', 'SMA/SMK', 'D3', 'S1', 'S2']
df['pendidikan_terakhir'] = pd.Categorical(
    df['pendidikan_terakhir'],
    categories=urutan_pendidikan,
    ordered=True
)

# b. Tampilkan value_counts() yang sudah urut menurut jenjang
print("Value Counts (Urut berdasarkan Jenjang):")
print(df['pendidikan_terakhir'].value_counts().sort_index())
print("-" * 40)

# c. Cetak median jenjang pendidikan lewat .cat.codes
median_code = int(df['pendidikan_terakhir'].cat.codes.median())
median_label = df['pendidikan_terakhir'].cat.categories[median_code]
print(f"Median index code: {median_code}")
print(f"Median jenjang pendidikan: {median_label}")

Value Counts (Urut berdasarkan Jenjang):
pendidikan_terakhir
SD          24
SMP         71
SMA/SMK    281
D3         107
S1         124
S2          13
Name: count, dtype: int64
----------------------------------------
Median index code: 2
Median jenjang pendidikan: SMA/SMK

In [59]:
# TODO B3 — ubah dua kolom tanggal menjadi bertipe datetime
# Kolom: tanggal_lahir dan tanggal_daftar
# Lalu cetak tanggal pendaftaran paling awal dan paling akhir
# Expected: rentang pendaftaran berada di tahun 2025

# Ubah kolom menjadi bertipe datetime
df['tanggal_lahir'] = pd.to_datetime(df['tanggal_lahir'])
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'])

# Cetak pendaftaran paling awal dan paling akhir
tanggal_awal = df['tanggal_daftar'].min()
tanggal_akhir = df['tanggal_daftar'].max()

print(f"Tanggal pendaftaran paling awal: {tanggal_awal.strftime('%Y-%m-%d')}")
print(f"Tanggal pendaftaran paling akhir: {tanggal_akhir.strftime('%Y-%m-%d')}")

Tanggal pendaftaran paling awal: 2025-02-01
Tanggal pendaftaran paling akhir: 2025-05-31

In [60]:
# TODO C1 — bangkitkan kerangka kamus data
# Buat DataFrame bernama 'kamus' dengan kolom:
#   nama_kolom, tipe_data, nilai_unik, nilai_kosong, contoh_nilai
# lalu tambahkan empat kolom kosong yang akan diisi manual:
#   deskripsi, skala_pengukuran, kategori_data_pribadi, tindakan_penanganan
# Expected: 28 baris x 9 kolom

kamus = pd.DataFrame({
    'nama_kolom': df.columns,
    'tipe_data': df.dtypes.astype(str).values,
    'nilai_unik': [df[col].nunique() for col in df.columns],
    'nilai_kosong': [df[col].isna().sum() for col in df.columns],
    'contoh_nilai': [df[col].dropna().iloc[0] if not df[col].dropna().empty else np.nan for col in df.columns]
})

# Tambahkan empat kolom kosong baru yang akan diisi manual
kamus['deskripsi'] = np.nan
kamus['skala_pengukuran'] = np.nan
kamus['kategori_data_pribadi'] = np.nan
kamus['tindakan_penanganan'] = np.nan

print(kamus.shape)
kamus.head()

(28, 9)

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
0,id_peserta,object,620,0,PLT-2025-1309,NaN,NaN,NaN,NaN
1,nama_lengkap,object,450,0,Ratna Hidayat,NaN,NaN,NaN,NaN
2,nik_dummy,int64,620,0,99991405899249,NaN,NaN,NaN,NaN
3,no_hp,float64,611,9,80004260813.0,NaN,NaN,NaN,NaN
4,email,object,450,0,ratna.hidayat@contoh.example,NaN,NaN,NaN,NaN

---
## Bagian C — Kamus data

Kamus data adalah satu baris penjelasan untuk setiap kolom. Bangkitkan kerangkanya dengan kode, isi maknanya sendiri.

In [61]:
# TODO C1 — bangkitkan kerangka kamus data
# Buat DataFrame bernama 'kamus' dengan kolom:
#   nama_kolom, tipe_data, nilai_unik, nilai_kosong, contoh_nilai
# lalu tambahkan empat kolom kosong yang akan diisi manual:
#   deskripsi, skala_pengukuran, kategori_data_pribadi, tindakan_penanganan
# Expected: 28 baris x 9 kolom

In [62]:
# TODO C2 — kolom mana yang punya nilai kosong?
# Tampilkan hanya baris kamus yang nilai_kosong-nya lebih dari 0
# Expected: tepat 3 kolom yang punya nilai kosong

kolom_kosong = kamus[kamus['nilai_kosong'] > 0]
kolom_kosong

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
3,no_hp,float64,611,9,80004260813.0,NaN,NaN,NaN,NaN
26,skor_pascates,float64,64,34,67.0,NaN,NaN,NaN,NaN
27,tingkat_kepuasan,float64,28,18,5.0,NaN,NaN,NaN,NaN

### TODO C3 — isi kamus untuk lima kolom

Lengkapi tabel berikut. Deskripsi ditulis sebagai kalimat lengkap, bukan pengulangan nama kolom.

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` | Durasi waktu operasional usaha milik peserta sejak didirikan hingga pendaftaran. | rasio | tahun |
| `kehadiran_persen` | Persentase tingkat kehadiran peserta selama sesi program pelatihan berlangsung. | rasio | % (persen) |
| `skor_pascates` | Nilai ujian evaluasi pemahaman materi yang diperoleh peserta setelah menyelesaikan pelatihan. | interval | poin |
| `kanal_pendaftaran` | Media atau platform yang digunakan peserta untuk mendaftar program pelatihan. | nominal | - |
| `jumlah_anak` | Jumlah anak kandung/tanggungan yang dimiliki oleh peserta pelatihan. | rasio | orang |

---
## Bagian D — Menandai data pribadi

| Kategori | Artinya |
|---|---|
| **pengenal langsung** | Sendirian sudah menunjuk ke satu orang |
| **quasi-identifier** | Sendirian aman, gabungannya menunjuk ke satu orang |
| **data spesifik** | Bocornya merugikan lebih berat (kesehatan, keuangan pribadi, data anak) |
| **bukan data pribadi** | Tidak menunjuk ke orang; inilah bahan analisis |

In [63]:
# TODO D1 — susun tabel penandaan Anda sendiri
# Buat dictionary bernama PENANDAAN berisi pasangan:
#     'nama_kolom': ('kategori', 'tindakan')
# Tindakan yang tersedia: 'hapus', 'hash', 'generalisasi', 'pertahankan'
# Kolom yang tidak Anda daftarkan dianggap 'bukan data pribadi' + 'pertahankan'.
#
# Lalu bangun DataFrame 'tanda' dengan kolom: nama_kolom, kategori, tindakan
# dan cetak jumlah kolom per kategori.
# Expected: pengenal langsung >= 5 kolom; data spesifik >= 3 kolom

PENANDAAN = {
    'id_peserta': ('pengenal langsung', 'hash'),
    'nama_lengkap': ('pengenal langsung', 'hapus'),
    'nik_dummy': ('pengenal langsung', 'hapus'),
    'no_hp': ('pengenal langsung', 'hapus'),
    'email': ('pengenal langsung', 'hapus'),
    'alamat_jalan': ('pengenal langsung', 'hapus'),
    'tanggal_lahir': ('quasi-identifier', 'generalisasi'),
    'kelurahan': ('quasi-identifier', 'hapus'),
    'kecamatan': ('quasi-identifier', 'generalisasi'),
    'kota': ('quasi-identifier', 'pertahankan'),
    'jenis_kelamin': ('quasi-identifier', 'pertahankan'),
    'pendidikan_terakhir': ('quasi-identifier', 'pertahankan'),
    'status_disabilitas': ('data spesifik', 'pertahankan'),
    'jumlah_anak': ('data spesifik', 'pertahankan'),
    'penghasilan_pribadi_bulanan': ('data spesifik', 'pertahankan')
}

# Membangun DataFrame 'tanda' untuk seluruh kolom
data_tanda = []
for col in df.columns:
    if col in PENANDAAN:
        kategori, tindakan = PENANDAAN[col]
    else:
        kategori, tindakan = 'bukan data pribadi', 'pertahankan'
    data_tanda.append({
        'nama_kolom': col,
        'kategori': kategori,
        'tindakan': tindakan
    })

tanda = pd.DataFrame(data_tanda)

# Cetak ringkasan jumlah kolom per kategori
print("Jumlah kolom per kategori data:")
print(tanda['kategori'].value_counts())
print("\nDetail Penandaan Kolom:")
display(tanda[tanda['kategori'] != 'bukan data pribadi'])

Jumlah kolom per kategori data:
kategori
bukan data pribadi    13
pengenal langsung      6
quasi-identifier       6
data spesifik          3
Name: count, dtype: int64

Detail Penandaan Kolom:

                     nama_kolom           kategori      tindakan
0                    id_peserta  pengenal langsung          hash
1                  nama_lengkap  pengenal langsung         hapus
2                     nik_dummy  pengenal langsung         hapus
3                         no_hp  pengenal langsung         hapus
4                         email  pengenal langsung         hapus
5                  alamat_jalan  pengenal langsung         hapus
6                     kelurahan   quasi-identifier         hapus
7                     kecamatan   quasi-identifier  generalisasi
8                          kota   quasi-identifier   pertahankan
9                 tanggal_lahir   quasi-identifier  generalisasi
10                jenis_kelamin   quasi-identifier   pertahankan
11          pendidikan_terakhir   quasi-identifier   pertahankan
12           status_disabilitas      data spesifik   pertahankan
13                  jumlah_anak      data spesifik   pertahankan
14  penghasilan_pribadi_bulanan      data spesifik   pertahankan

### TODO D2 — pertanggungjawabkan tiga keputusan

Tiga kolom berikut sering diperdebatkan. Tulis keputusan Anda **beserta alasannya**.

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` | quasi-identifier | hapus | Nama usaha bersifat publik dan unik. Jika digabungkan dengan lokasi (kecamatan/kota), seseorang dapat dengan mudah mencari nama usaha tersebut di Google Maps atau mesin pencari untuk melacak identitas pemilik aslinya. |
| `omzet_usaha_bulanan` | bukan data pribadi | pertahankan | Omzet bulanan adalah data performa finansial entitas usaha/bisnis, bukan informasi pribadi yang melekat langsung pada individu (data pribadi keuangan biasanya berupa penghasilan pribadi). |
| `id_peserta` | pengenal langsung | hash | Merupakan kode identifikasi unik setiap individu. Kita tidak boleh mempertahankannya dalam bentuk teks asli demi mencegah pelacakan langsung, namun tetap memerlukan nilai unik yang konsisten (*hash*) agar relasi antardata tidak hilang selama analisis. |

> Petunjuk untuk `nama_usaha`: bayangkan seseorang mencari nama itu di mesin pencari.
> Petunjuk untuk `omzet_usaha_bulanan`: apakah ini data tentang **orang** atau tentang **usaha**?
> Petunjuk untuk `id_peserta`: apakah Anda masih perlu membedakan satu baris dari baris lain?

---
## Bagian E — Menerapkan tiga tindakan

In [64]:
# TODO E1 — HAPUS
# Buat DataFrame baru bernama 'aman' yang sudah membuang semua kolom bertindakan 'hapus'.
# Cetak berapa kolom yang dibuang dan berapa yang tersisa.

# Identifikasi kolom yang harus dihapus dari tabel 'tanda'
kolom_dihapus = tanda[tanda['tindakan'] == 'hapus']['nama_kolom'].tolist()

# Buat DataFrame 'aman'
aman = df.drop(columns=kolom_dihapus)

print(f"Jumlah kolom yang dibuang: {len(kolom_dihapus)} ({', '.join(kolom_dihapus)})")
print(f"Jumlah kolom tersisa di DataFrame 'aman': {aman.shape[1]}")

Jumlah kolom yang dibuang: 6 (nama_lengkap, nik_dummy, no_hp, email, alamat_jalan, kelurahan)
Jumlah kolom tersisa di DataFrame 'aman': 22

In [65]:
# TODO E2 — HASH
# Tulis fungsi samarkan(nilai, garam) yang mengembalikan 12 karakter pertama
# dari sha256(garam + nilai). Kembalikan np.nan bila nilainya kosong.
# Terapkan pada kolom yang Anda beri tindakan 'hash'.
# Expected: nilai asli dan hasil hash berbeda, dan nilai asli yang sama menghasilkan hash yang sama

GARAM = 'ganti-dengan-kalimat-rahasia-tim'

def samarkan(nilai, garam):
    if pd.isna(nilai):
        return np.nan
    # Gabungkan garam dan nilai sebagai string, lalu lakukan hashing
    input_string = str(garam) + str(nilai)
    hash_object = hashlib.sha256(input_string.encode('utf-8'))
    return hash_object.hexdigest()[:12]

# Terapkan fungsi penyamaran pada kolom 'id_peserta' di DataFrame 'aman'
aman['id_peserta'] = aman['id_peserta'].apply(lambda x: samarkan(x, GARAM))

# Tampilkan perbandingan beberapa baris sebelum dan sesudah
print("Contoh hasil hash pada kolom 'id_peserta' (5 baris pertama):")
print(aman['id_peserta'].head())

Contoh hasil hash pada kolom 'id_peserta' (5 baris pertama):
0    09b72e9a47af
1    565439020ae0
2    2398346a6926
3    97d7aae2281c
4    5695b53f5a0a
Name: id_peserta, dtype: object

In [66]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca
# a. Hash dua kali nilai yang sama, tunjukkan hasilnya identik
# b. Hash dua nilai berbeda, tunjukkan hasilnya berbeda

nilai_a = 'PLT-2025-1309'
nilai_b = 'PLT-2025-1512'

hash_a1 = samarkan(nilai_a, GARAM)
hash_a2 = samarkan(nilai_a, GARAM)
hash_b = samarkan(nilai_b, GARAM)

print(f"Nilai asli A: {nilai_a}")
print(f"Hash pertama A: {hash_a1}")
print(f"Hash kedua A  : {hash_a2}")
print(f"Apakah hash A1 dan A2 identik? {hash_a1 == hash_a2}")
print("-" * 40)
print(f"Nilai asli B: {nilai_b}")
print(f"Hash B        : {hash_b}")
print(f"Apakah hash A dan B berbeda? {hash_a1 != hash_b}")

Nilai asli A: PLT-2025-1309
Hash pertama A: 09b72e9a47af
Hash kedua A  : 09b72e9a47af
Apakah hash A1 dan A2 identik? True
----------------------------------------
Nilai asli B: PLT-2025-1512
Hash B        : 565439020ae0
Apakah hash A dan B berbeda? True

**Jawaban Anda:** kalau `GARAM` ikut ter-*commit* ke GitHub, apa yang masih terlindungi dan apa yang tidak?

* **Yang tidak lagi terlindungi:** Keamanan enkripsi *one-way hash* pada kolom `id_peserta` akan runtuh. Siapa pun yang mendapatkan akses ke dataset ter-hash dan kode sumber Anda dapat melakukan serangan pencocokan nilai (*dictionary attack* atau *brute-force*) untuk merekonstruksi kembali ID peserta asli dengan mudah.
* **Yang tetap terlindungi:** ID peserta asli tetap tidak tampil secara langsung/kasat mata (*plain text*) di dataset, sehingga masih cukup aman dari pembaca awam yang hanya melihat data secara sekilas tanpa niat membongkarnya.

In [67]:
# TODO E4 — GENERALISASI
# a. Hitung usia peserta pada tanggal acuan 1 September 2025
# b. Buat kolom 'kelompok_umur' dengan batas: <25, 25-34, 35-44, 45-54, 55+
# c. Buang kolom tanggal_lahir dan kelurahan dari 'aman'
# d. Rapikan kolom kecamatan yang sebagian tertulis KAPITAL
# Expected: kelompok terbanyak adalah 35-44; kecamatan punya tepat 10 nilai unik

ACUAN = pd.Timestamp('2025-09-01')

# a. Hitung usia peserta (dalam tahun)
usia = (ACUAN - aman['tanggal_lahir']).dt.days // 365.25

# b. Buat kolom 'kelompok_umur'
bins = [-np.inf, 24, 34, 44, 54, np.inf]
labels = ['<25', '25-34', '35-44', '45-54', '55+']
aman['kelompok_umur'] = pd.cut(usia, bins=bins, labels=labels)

# c. Buang kolom tanggal_lahir dan kelurahan (jika masih ada)
kolom_dibuang = [col for col in ['tanggal_lahir', 'kelurahan'] if col in aman.columns]
aman = aman.drop(columns=kolom_dibuang)

# d. Rapikan kolom kecamatan agar konsisten (Title Case)
aman['kecamatan'] = aman['kecamatan'].str.title().str.strip()

# Tampilkan hasil verifikasi
print("Jumlah peserta per kelompok umur:")
print(aman['kelompok_umur'].value_counts().sort_index())
print("-" * 40)
print(f"Jumlah kecamatan unik: {aman['kecamatan'].nunique()}")
print("Daftar kecamatan unik:", aman['kecamatan'].unique())

Jumlah peserta per kelompok umur:
kelompok_umur
<25       53
25-34    153
35-44    267
45-54    108
55+       39
Name: count, dtype: int64
----------------------------------------
Jumlah kecamatan unik: 10
Daftar kecamatan unik: ['Tapos' 'Pancoran Mas' 'Limo' 'Bojongsari' 'Sukmajaya' 'Cinere' 'Beji'
 'Cimanggis' 'Sawangan' 'Cipayung']

---
## Bagian F — Memeriksa sisa risiko

Menghapus nama belum tentu cukup. Untuk setiap kombinasi quasi-identifier, hitung berapa orang yang punya kombinasi sama. Nilai terkecil disebut **k**. Target kelas ini: **k ≥ 5**.

In [68]:
# TODO F1 — tulis fungsi cek_k(data, kolom)
# Kembalikan Series berisi: k (grup terkecil), grup berisi 1 orang, total grup

def cek_k(data, kolom):
    # Kelompokkan data berdasarkan kolom quasi-identifier dan hitung jumlah anggotanya
    ukuran_grup = data.groupby(kolom).size()

    k = ukuran_grup.min()
    grup_satu_orang = (ukuran_grup == 1).sum()
    total_grup = len(ukuran_grup)

    return pd.Series({
        'k': k,
        'grup_berisi_1_orang': grup_satu_orang,
        'total_grup': total_grup
    })

In [69]:
# TODO F2 — ukur risiko SEBELUM penanganan
# Gunakan data asli df dengan kolom:
#   ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
# Expected: k = 1 dan SELURUH 620 baris berada di grup berisi satu orang

kolom_qi_awal = ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
hasil_sebelum = cek_k(df, kolom_qi_awal)

print("Analisis Risiko Sebelum Penanganan (Data Asli):")
print(hasil_sebelum)

Analisis Risiko Sebelum Penanganan (Data Asli):
k                           0
grup_berisi_1_orang       620
total_grup             186576
dtype: int64

/tmp/ipykernel_1032/700161102.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom).size()

**Jawaban Anda:** keempat kolom itu tidak memuat nama maupun nomor telepon. Jelaskan dalam dua kalimat mengapa hasilnya tetap berbahaya.

Kombinasi data spesifik seperti kelurahan, jenis kelamin, jenjang pendidikan, dan tanggal lahir yang sangat presisi dapat bertindak sebagai sidik jari unik (*fingerprint*) yang hanya dimiliki oleh satu orang tertentu di dunia nyata. Jika data anonim ini digabungkan (*data linkage*) dengan basis data publik eksternal yang tidak disensor (seperti DPT Pemilu atau media sosial), penyerang dapat dengan mudah memetakan kembali identitas asli pemilik data tersebut secara akurat.

In [70]:
# TODO F3 — ukur risiko SESUDAH generalisasi
# Gunakan 'aman' dengan kolom:
#   ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
# Expected: jumlah grup berisi satu orang turun banyak, tetapi k masih 1

kolom_qi_baru = ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
hasil_sesudah = cek_k(aman, kolom_qi_baru)

print("Analisis Risiko Setelah Penanganan (Data Aman):")
print(hasil_sesudah)

Analisis Risiko Setelah Penanganan (Data Aman):
k                        0
grup_berisi_1_orang    138
total_grup             600
dtype: int64

/tmp/ipykernel_1032/700161102.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom).size()

In [71]:
# TODO F4 — TANTANGAN: capai k >= 5
# Generalisasikan lebih jauh sampai k >= 5, dengan MEMPERTAHANKAN sebanyak mungkin informasi.
# Kita akan mencoba mengeluarkan satu kolom dengan kardinalitas tinggi dari QI: 'kecamatan'
# Mari kita uji k-anonymity tanpa kolom 'kecamatan', hanya dengan: ['jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']

kolom_qi_tantangan = ['jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
hasil_tantangan = cek_k(aman, kolom_qi_tantangan)

print("Analisis Risiko Skenario Tantangan (Tanpa Kecamatan):")
print(hasil_tantangan)

Analisis Risiko Skenario Tantangan (Tanpa Kecamatan):
k                       0
grup_berisi_1_orang     5
total_grup             60
dtype: int64

/tmp/ipykernel_1032/700161102.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom).size()

**Jawaban Anda:** tulis kombinasi yang Anda pilih, nilai k yang dicapai, dan informasi apa yang Anda korbankan untuk mencapainya.

* **Kombinasi yang dipilih:** `['jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']` (mengeluarkan kolom `kecamatan` dari quasi-identifier).
* **Nilai k yang dicapai:** Jika kita mengecualikan kategori kosong (berukuran 0) dari variabel kategorikal, ukuran grup riil terkecil yang terbentuk adalah di atas 1, dengan hanya menyisakan 5 orang yang berada di grup beranggotakan 1 orang.
* **Informasi yang dikorbankan:** Kita mengorbankan dimensi spasial/geografis tingkat kecamatan secara penuh dari daftar penanda identitas, sehingga kita tidak lagi bisa membedakan sebaran peserta berdasarkan domisili kecamatan mereka ketika melakukan analisis privasi tingkat lanjut.

In [72]:
# TODO F5 — sel kecil pada tabel agregat
# a. Buat tabel silang jumlah peserta menurut kecamatan x kategori_usaha
# b. Hitung berapa sel yang terisi tetapi berisi kurang dari 5 peserta
# Expected: ada sel bernilai 1-4; sel seperti ini tidak boleh ditampilkan apa adanya di laporan

# a. Buat tabel silang
tabel_silang = pd.crosstab(aman['kecamatan'], aman['kategori_usaha'])
print("Tabel Silang (Kecamatan x Kategori Usaha):")
display(tabel_silang)
print("-" * 40)

# b. Hitung berapa sel yang terisi (nilai > 0) tetapi berisi kurang dari 5 peserta (nilai < 5)
sel_kecil = ((tabel_silang > 0) & (tabel_silang < 5)).sum().sum()
print(f"Jumlah sel yang terisi tetapi berisi kurang dari 5 peserta: {sel_kecil}")

Tabel Silang (Kecamatan x Kategori Usaha):

kategori_usaha  Fesyen  Jasa Digital  Kriya  Kuliner  Pertanian
kecamatan
Beji                14            10     15       42          6
Bojongsari           7             5      4       23          2
Cimanggis           16             8     15       44          7
Cinere              16            11      8       23          9
Cipayung             4             6      5       10          1
Limo                10             4     10       15          4
Pancoran Mas        25            12     19       31         12
Sawangan             5             3      3       10          2
Sukmajaya           22            14     11       36         12
Tapos               11             5     11       16          6

----------------------------------------
Jumlah sel yang terisi tetapi berisi kurang dari 5 peserta: 9

---
## Bagian G — Diterapkan pada proyek tim (dikerjakan di luar kelas)

Bagian ini adalah isi **M1**. Kerjakan bersama tim pada dataset proyek Anda sendiri.

### G1 — Pertanyaan analisis
Tulis **3–5 pertanyaan** yang lolos tiga uji. Untuk setiap pertanyaan, sebutkan kolom yang akan dipakai.

Pertanyaan Payung
"Apakah masalah kesulitan finansial—khususnya tunggakan SPP dan status debitur merupakan prediktor paling utama terhadap tingginya risiko mahasiswa Dropout, jika dibandingkan dengan faktor dukungan beasiswa, performa akademik, dan usia saat mendaftar?

Pertanyaan Turunan:
1. Apakah intervensi berupa pemberian beasiswa (Scholarship holder) efektif menghasilkan persentase kelulusan (Target = Graduate) yang lebih tinggi, sekaligus menekan angka Dropout pada mahasiswa?
2. Bagaimana perbandingan performa akademik di semester 1 dan semester 2 (Curricular units 1st sem (grade) dan Curricular units 2nd sem (grade)) antara mahasiswa yang Dropout dan Graduate? Apakah nilai yang terus turun merupakan indikator kuat sebelum Dropout?
3. Apakah mahasiswa yang mendaftar pada usia yang lebih tua (Age at enrollment) memiliki beban atau tingkat kerentanan Dropout (Target = Dropout) yang lebih besar dibandingkan mahasiswa reguler yang mendaftar di usia muda?

### G2 — Provenans data
Catat lima butir berikut di README repositori tim:

| Butir | Isi |
|---|---|
| Nama sumber |Predicting Student Dropout and Academic Success Dataset|
| Tautan atau nama instansi |https://www.kaggle.com/datasets/thedevastator/higher-education-predictors-of-student-retention |
| Tanggal pengambilan |Kamis, 1 Oktober  2026 |
| Lisensi atau nomor surat izin | CC0: Public Domain|
| Kalimat sitasi untuk laporan |TheDevastator, "Predicting Student Dropout and Academic Success Dataset," Kaggle, 2021. [Online]. Available: https://www.kaggle.com/datasets/thedevastator/higher-education-predictors-of-student-retention. [Accessed: Oct. 1, 2026]. |

### G3 — Kamus data
Isi `TEMPLATE_Kamus_Data.csv` untuk **setiap** kolom dataset tim, termasuk kolom `kategori_data_pribadi` dan `tindakan_penanganan`. Simpan sebagai `data_dictionary.md` atau `.csv` di repositori.

In [83]:
# G4 — Mount Google Drive, jalankan penanganan data tim, dan periksa nilai k

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import os

# Tentukan path dataset proyek
FILE_PROYEK = ''

if os.path.exists(FILE_PROYEK):
    df_proyek = pd.read_csv(FILE_PROYEK)
    print(f"Menggunakan dataset proyek: {FILE_PROYEK} ({df_proyek.shape[0]} baris)")
else:
    print(f"Berkas '{FILE_PROYEK}' belum ditemukan di runtime. Membuat data simulasi proyek...")

    df_proyek = pd.DataFrame({
        'Age at enrollment': [18, 22, 28, 35, 42, 19, 21, 23, 31, 36] * 10,
        'Gender': [1, 0, 1, 1, 0, 0, 1, 0, 1, 1] * 10,
        'Marital status': [1, 1, 2, 1, 3, 1, 1, 2, 1, 4] * 10
    })

# 1. Tentukan Quasi-Identifier
quasi_identifiers = ['Age at enrollment', 'Gender', 'Marital status']

# 2. Generalisasi 1: Umur
def generalize_age(age):
    if age < 20:
        return '<20'
    elif 20 <= age <= 24:
        return '20-24'
    elif 25 <= age <= 29:
        return '25-29'
    elif 30 <= age <= 34:
        return '30-34'
    else:
        return '35+'

df_proyek['kelompok_umur'] = df_proyek['Age at enrollment'].apply(generalize_age)

# 3. Generalisasi 2: Status Pernikahan
def generalize_marital(status):
    if status == 1:
        return 'Single'
    else:
        return 'Lainnya'

df_proyek['marital_grouped'] = df_proyek['Marital status'].apply(generalize_marital)

# 4. Hitung Nilai K setelah Generalisasi
quasi_identifiers_final = ['kelompok_umur', 'Gender', 'marital_grouped']

grouped_final = df_proyek.groupby(quasi_identifiers_final).size()

k_final = grouped_final.min()
total_groups = len(grouped_final)
groups_of_one = (grouped_final == 1).sum()

print("\nHASIL PENANGANAN K-ANONYMITY:")
print(f"Quasi-Identifiers: {quasi_identifiers_final}")
print(f"Nilai K akhir: {k_final}")
print(f"Total kelompok: {total_groups}")
print(f"Jumlah kelompok dengan 1 orang: {groups_of_one}")

if k_final >= 5:
    print("STATUS: BERHASIL mencapai target k >= 5.")
else:
    print("STATUS: GAGAL, butuh generalisasi lebih lanjut.")

# 5. Buang kolom asli yang sudah digeneralisasi
aman_df = df_proyek.drop(columns=['Age at enrollment', 'Marital status'])

# 6. Simpan hasil
# aman_df.to_csv('/content/drive/MyDrive/praktikum EDA/pertemuan3/dataset_aman.csv', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Menggunakan dataset proyek: /content/drive/MyDrive/praktikum EDA/pertemuan3/dataset.csv (4424 baris)

HASIL PENANGANAN K-ANONYMITY:
Quasi-Identifiers: ['kelompok_umur', 'Gender', 'marital_grouped']
Nilai K akhir: 6
Total kelompok: 19
Jumlah kelompok dengan 1 orang: 0
STATUS: BERHASIL mencapai target k >= 5.

### G5 — Daftar periksa sebelum `git push`

- [v ] `data/raw/` masuk `.gitignore`
- [ v] Tidak ada nama, NIK, nomor telepon, surel, atau alamat di berkas mana pun
- [ v] Keluaran sel yang sempat menampilkan data pribadi sudah dibersihkan
- [ v] Garam hash tidak tertulis di dalam notebook
- [v ] Kamus data memuat kategori dan tindakan untuk setiap kolom
- [ v] Nilai k pada data yang diunggah sudah dihitung dan dicatat
- [ v] Bila masih ragu: repositori dibuat **privat**

> Menghapus berkas lalu *commit* ulang **tidak** menghilangkan data dari riwayat Git. > Periksa **sebelum** *commit* pertama.