# Praktikum Pertemuan 3 — Menyiapkan Data Proyek agar Layak dan Aman Dianalisis

**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 3  
**Fase PjBL:** Perencanaan  
**Sub-CPMK3:** Mahasiswa mampu merumuskan pertanyaan analisis dari masalah nyata serta memperoleh data
sesuai lisensi sumbernya, serta mengidentifikasi dan menangani data pribadi yang terkandung di dalamnya (C4, A3).

**Cara kerja.** Sel bertanda `# TODO` Anda kerjakan sendiri; setiap TODO disertai *expected output* agar Anda bisa memeriksa jawaban sendiri. Sel Markdown bertanda **Jawaban Anda** diisi dengan tulisan, bukan kode.

**Bagian A–F** dikerjakan di kelas dengan dataset latihan. **Bagian G** dikerjakan bersama tim di luar kelas dengan dataset proyek Anda sendiri, dan hasilnya menjadi isi **M1 (bobot 5%)** yang dikumpulkan sesuai tenggat di LMS.

## Bagian 0 — Persiapan

Dataset latihan: **`peserta_pelatihan_umkm_2025.csv`** — 620 baris, 28 kolom.
Data pendaftaran dan hasil pelatihan UMKM binaan kampus.

> **Catatan penting:** seluruh isi dataset ini **sintetis** dan dibuat untuk latihan. Tidak ada orang nyata di dalamnya.
> Nomor NIK, nomor telepon, dan surel sengaja dibuat dengan pola yang tidak valid. Perlakukan tetap seolah-olah data nyata,
> karena itulah kebiasaan yang sedang kita latih.

In [28]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)
print('pandas', pd.__version__)

pandas 2.2.3

In [29]:
FILE = '/content/drive/MyDrive/SEMESTER 3/Expolatory D. Analisys/Pertemuan03/data/peserta_pelatihan_umkm_2025.csv'

# Make sure to run the `drive.mount('/content/drive')` cell (cell ID: TqTAPDt1Itwa) first!

if not os.path.exists(FILE):
    raise FileNotFoundError(f"/content/drive/MyDrive/SEMESTER 3/Expolatory D. Analisys/Pertemuan03/data/peserta_pelatihan_umkm_2025.csv")

df = pd.read_csv(FILE)
print(df.shape)
df.head(3)

(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

In [30]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

---
## Bagian A — Merumuskan pertanyaan analisis

Sebuah pertanyaan analisis dianggap layak bila lolos **tiga uji**:

1. **Uji kolom** — kolom mana yang akan menjawabnya?
2. **Uji bentuk jawaban** — jawabannya berupa angka, peringkat, perbandingan, atau sebaran?
3. **Uji tindak lanjut** — kalau terjawab, apa yang bisa diputuskan?

In [31]:
# TODO A1 — kenali kolom yang tersedia sebelum menulis pertanyaan

import pandas as pd

FILE = '/content/drive/MyDrive/SEMESTER 3/Expolatory D. Analisys/Pertemuan03/data/peserta_pelatihan_umkm_2025.csv'
df = pd.read_csv(FILE)

# a. Cetak daftar nama kolom beserta tipe datanya
print("Daftar kolom dan tipe data:")
display(df.dtypes.to_frame('tipe_data'))

# b. Tampilkan nama kolom saja agar mudah dipakai saat merumuskan pertanyaan.
print("\nNama kolom:")
print(df.columns.tolist())

Daftar kolom dan tipe data:

                            tipe_data
id_peserta                     object
nama_lengkap                   object
nik_dummy                       int64
no_hp                         float64
email                          object
alamat_jalan                   object
kelurahan                      object
kecamatan                      object
kota                           object
tanggal_lahir                  object
jenis_kelamin                  object
pendidikan_terakhir            object
status_disabilitas             object
jumlah_anak                     int64
penghasilan_pribadi_bulanan     int64
nama_usaha                     object
kategori_usaha                 object
produk_utama                   object
lama_usaha_tahun              float64
jumlah_karyawan                 int64
omzet_usaha_bulanan             int64
pernah_ikut_pelatihan          object
kanal_pendaftaran              object
tanggal_daftar                 object
kehadiran_persen                int64
skor_prates                     int64
skor_pascates                 float64
tingkat_kepuasan              float64

Nama kolom:
['id_peserta', 'nama_lengkap', 'nik_dummy', 'no_hp', 'email', 'alamat_jalan', 'kelurahan', 'kecamatan', 'kota', 'tanggal_lahir', 'jenis_kelamin', 'pendidikan_terakhir', 'status_disabilitas', 'jumlah_anak', 'penghasilan_pribadi_bulanan', 'nama_usaha', 'kategori_usaha', 'produk_utama', 'lama_usaha_tahun', 'jumlah_karyawan', 'omzet_usaha_bulanan', 'pernah_ikut_pelatihan', 'kanal_pendaftaran', 'tanggal_daftar', 'kehadiran_persen', 'skor_prates', 'skor_pascates', 'tingkat_kepuasan']

In [32]:

# b. Cetak jumlah baris dan kolom
print("\nUkuran dataset:")
print(df.shape)

Ukuran dataset:
(620, 28)

### TODO A2 — perbaiki tiga pertanyaan berikut

Tulis versi perbaikannya di sel di bawah, beserta kolom yang akan dipakai.

| No | Draf pertanyaan | Masalahnya |
|---|---|---|
| 1 | Bagaimana kondisi peserta pelatihan? | Terlalu kabur |
| 2 | Apakah peserta yang lebih kaya lebih sukses? | "Kaya" dan "sukses" belum didefinisikan sebagai kolom |
| 3 | Apakah pelatihan menaikkan omzet peserta? | Uji kolom gagal — cek sendiri mengapa |

**Jawaban Anda:**

1. **Perbaikan:** Bagaimana sebaran tingkat kepuasan peserta setelah mengikuti pelatihan?  
   **Kolom:** `tingkat_kepuasan`

2. **Perbaikan:** Apakah peserta dengan omzet usaha bulanan yang lebih tinggi memiliki skor pascates yang lebih tinggi?  
   **Kolom:** `omzet_usaha_bulanan`, `skor_pascates`

3. **Perbaikan:** Bagaimana sebaran omzet usaha bulanan peserta saat mendaftar pelatihan?  
   **Kolom:** `omzet_usaha_bulanan`

**Mengapa pertanyaan asli nomor 3 gagal:** dataset hanya menyediakan omzet usaha saat mendaftar, tidak menyediakan kolom omzet sesudah pelatihan. Karena itu, kenaikan omzet sebelum dan sesudah pelatihan tidak dapat diukur dari dataset ini.

In [33]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.

kolom_omzet = [kolom for kolom in df.columns if 'omzet' in kolom.lower()]

print("Kolom yang mengandung kata 'omzet':")
print(kolom_omzet)

if len(kolom_omzet) == 1:
    print("Kesimpulan: hanya ada satu kolom omzet, yaitu data omzet saat mendaftar.")
else:
    print("Periksa kembali kolom omzet yang tersedia.")

Kolom yang mengandung kata 'omzet':
['omzet_usaha_bulanan']
Kesimpulan: hanya ada satu kolom omzet, yaitu data omzet saat mendaftar.

---
## Bagian B — Skala pengukuran

### TODO B1 — klasifikasikan delapan kolom berikut

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` | **Nominal** | Berisi kategori jenis usaha dan tidak memiliki urutan tingkatan. |
| `pendidikan_terakhir` | **Ordinal** | Jenjang pendidikan memiliki urutan dari SD sampai S2. |
| `skor_prates` | **Rasio** | Berupa skor numerik dengan nol sebagai titik yang bermakna dan dapat dibandingkan secara rasio. |
| `omzet_usaha_bulanan` | **Rasio** | Nilai uang memiliki nol yang bermakna dan perbandingan dua kali lipat dapat diinterpretasikan. |
| `jumlah_karyawan` | **Rasio** | Merupakan hitungan dengan nol yang bermakna. |
| `tingkat_kepuasan` | **Ordinal** | Tingkat kepuasan memiliki urutan, tetapi jarak antar tingkat belum tentu sama. |
| `tanggal_daftar` | **Interval** | Selisih antar tanggal bermakna, tetapi tidak memiliki nol absolut. |
| `kecamatan` | **Nominal** | Nama kecamatan hanya membedakan kelompok dan tidak memiliki urutan. |

In [34]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe

urutan_pendidikan = ['SD', 'SMP', 'SMA/SMK', 'D3', 'S1', 'S2']

df['pendidikan_terakhir'] = pd.Categorical(
    df['pendidikan_terakhir'],
    categories=urutan_pendidikan,
    ordered=True
)

print("Distribusi pendidikan berdasarkan urutan jenjang:")
print(df['pendidikan_terakhir'].value_counts(sort=False))

median_kode = df['pendidikan_terakhir'].cat.codes.replace(-1, np.nan).median()
median_jenjang = urutan_pendidikan[int(median_kode)]

print("\nMedian kode:", median_kode)
print("Median jenjang pendidikan:", median_jenjang)

Distribusi pendidikan berdasarkan urutan jenjang:
pendidikan_terakhir
SD          24
SMP         71
SMA/SMK    281
D3         107
S1         124
S2          13
Name: count, dtype: int64

Median kode: 2.0
Median jenjang pendidikan: SMA/SMK

In [35]:
# TODO B3 — ubah dua kolom tanggal menjadi bertipe datetime

df['tanggal_lahir'] = pd.to_datetime(df['tanggal_lahir'], errors='coerce')
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'], errors='coerce')

print("Tipe data tanggal_lahir :", df['tanggal_lahir'].dtype)
print("Tipe data tanggal_daftar:", df['tanggal_daftar'].dtype)

print("\nTanggal pendaftaran paling awal :", df['tanggal_daftar'].min())
print("Tanggal pendaftaran paling akhir:", df['tanggal_daftar'].max())

Tipe data tanggal_lahir : datetime64[ns]
Tipe data tanggal_daftar: datetime64[ns]

Tanggal pendaftaran paling awal : 2025-02-01 00:00:00
Tanggal pendaftaran paling akhir: 2025-05-31 00:00:00

---
## Bagian C — Kamus data

Kamus data adalah satu baris penjelasan untuk setiap kolom. Bangkitkan kerangkanya dengan kode, isi maknanya sendiri.

In [36]:
# TODO C1 — bangkitkan kerangka kamus data

kamus = pd.DataFrame({
    'nama_kolom': df.columns,
    'tipe_data': [str(df[col].dtype) for col in df.columns],
    'nilai_unik': [df[col].nunique(dropna=True) for col in df.columns],
    'nilai_kosong': [df[col].isna().sum() for col in df.columns],
    'contoh_nilai': [
        df[col].dropna().iloc[0] if df[col].notna().any() else np.nan
        for col in df.columns
    ]
})

for kolom in [
    'deskripsi',
    'skala_pengukuran',
    'kategori_data_pribadi',
    'tindakan_penanganan'
]:
    kamus[kolom] = ''

print("Ukuran kamus data:", kamus.shape)
display(kamus)

Ukuran kamus data: (28, 9)

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
0,id_peserta,object,620,0,PLT-2025-1309,,,,
1,nama_lengkap,object,450,0,Ratna Hidayat,,,,
2,nik_dummy,int64,620,0,99991405899249,,,,
3,no_hp,float64,611,9,80004260813.0,,,,
4,email,object,450,0,ratna.hidayat@contoh.example,,,,
5,alamat_jalan,object,620,0,Jl. Cempaka No. 106 RT 02/RW 10,,,,
6,kelurahan,object,26,0,Sukatani,,,,
7,kecamatan,object,19,0,Tapos,,,,
8,kota,object,1,0,Depok,,,,
9,tanggal_lahir,datetime64[ns],598,0,1989-05-14 00:00:00,,,,
10,jenis_kelamin,object,2,0,P,,,,
11,pendidikan_terakhir,category,6,0,SMP,,,,
12,status_disabilitas,object,2,0,Tidak,,,,
13,jumlah_anak,int64,5,0,3,,,,
14,penghasilan_pribadi_bulanan,int64,110,0,500000,,,,
15,nama_usaha,object,185,0,CV Mandiri Jaya,,,,
16,kategori_usaha,object,5,0,Kuliner,,,,
17,produk_utama,object,19,0,Roti dan kue,,,,
18,lama_usaha_tahun,float64,119,0,12.8,,,,
19,jumlah_karyawan,int64,11,0,4,,,,
20,omzet_usaha_bulanan,int64,293,0,2950000,,,,
21,pernah_ikut_pelatihan,object,2,0,Tidak,,,,
22,kanal_pendaftaran,object,4,0,Datang langsung,,,,
23,tanggal_daftar,datetime64[ns],120,0,2025-04-04 00:00:00,,,,
24,kehadiran_persen,int64,46,0,75,,,,
25,skor_prates,int64,64,0,52,,,,
26,skor_pascates,float64,64,34,67.0,,,,
27,tingkat_kepuasan,float64,28,18,5.0,,,,

In [37]:
# TODO C2 — kolom mana yang punya nilai kosong?

kolom_kosong = kamus[kamus['nilai_kosong'] > 0]

print("Kolom yang memiliki nilai kosong:")
display(kolom_kosong)

print("Jumlah kolom dengan nilai kosong:", len(kolom_kosong))

Kolom yang memiliki nilai kosong:

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
3,no_hp,float64,611,9,80004260813.0,,,,
26,skor_pascates,float64,64,34,67.0,,,,
27,tingkat_kepuasan,float64,28,18,5.0,,,,

Jumlah kolom dengan nilai kosong: 3

### TODO C3 — isi kamus untuk lima kolom

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` | Menunjukkan lamanya usaha peserta telah berjalan sejak mulai menjalankan usaha. | Rasio | Tahun |
| `kehadiran_persen` | Menunjukkan persentase kehadiran peserta selama mengikuti pelatihan. | Rasio | Persen (%) |
| `skor_pascates` | Menunjukkan nilai yang diperoleh peserta pada tes setelah pelatihan. | Rasio | Skor |
| `kanal_pendaftaran` | Menunjukkan media atau jalur yang digunakan peserta ketika mendaftar pelatihan. | Nominal | Kategori |
| `jumlah_anak` | Menunjukkan jumlah anak yang dimiliki peserta. | Rasio | Orang |

---
## Bagian D — Menandai data pribadi

| Kategori | Artinya |
|---|---|
| **pengenal langsung** | Sendirian sudah menunjuk ke satu orang |
| **quasi-identifier** | Sendirian aman, gabungannya menunjuk ke satu orang |
| **data spesifik** | Bocornya merugikan lebih berat (kesehatan, keuangan pribadi, data anak) |
| **bukan data pribadi** | Tidak menunjuk ke orang; inilah bahan analisis |

In [38]:
# TODO D1 — susun tabel penandaan Anda sendiri
# Daftar dibuat berdasarkan nama kolom yang benar-benar tersedia.
# Kolom yang tidak ada akan diabaikan agar kode tetap dapat dijalankan.

PENANDAAN = {}

def tambah_penandaan(nama, kategori, tindakan):
    if nama in df.columns:
        PENANDAAN[nama] = (kategori, tindakan)

# Pengenal langsung: dapat menunjuk/mengidentifikasi satu entitas secara langsung.
for nama in [
    'id_peserta', 'nama_peserta', 'nik', 'no_hp', 'nomor_telepon',
    'email', 'alamat'
]:
    tambah_penandaan(nama, 'pengenal langsung', 'hapus')

# Nama usaha dapat dicari secara publik sehingga diperlakukan sebagai quasi-identifier.
tambah_penandaan('nama_usaha', 'quasi-identifier', 'generalisasi')

# Data yang masih diperlukan untuk analisis tetapi perlu dipertimbangkan risikonya.
for nama in [
    'tanggal_lahir', 'kelurahan', 'kecamatan', 'jenis_kelamin',
    'pendidikan_terakhir'
]:
    tambah_penandaan(nama, 'quasi-identifier', 'generalisasi')

# Data spesifik usaha/ekonomi tidak langsung mengidentifikasi seseorang.
for nama in [
    'omzet_usaha_bulanan', 'jumlah_karyawan', 'lama_usaha_tahun',
    'modal_usaha', 'kategori_usaha', 'kehadiran_persen',
    'skor_prates', 'skor_pascates', 'tingkat_kepuasan',
    'kanal_pendaftaran', 'jumlah_anak'
]:
    tambah_penandaan(nama, 'data spesifik', 'pertahankan')

tanda = pd.DataFrame(
    [
        {'nama_kolom': col, 'kategori': 'bukan data pribadi', 'tindakan': 'pertahankan'}
        for col in df.columns
    ]
)

for nama, (kategori, tindakan) in PENANDAAN.items():
    tanda.loc[tanda['nama_kolom'] == nama, ['kategori', 'tindakan']] = kategori, tindakan

print("Penandaan:")
display(tanda)

print("\nJumlah kolom per kategori:")
print(tanda['kategori'].value_counts())

Penandaan:

                     nama_kolom            kategori      tindakan
0                    id_peserta   pengenal langsung         hapus
1                  nama_lengkap  bukan data pribadi   pertahankan
2                     nik_dummy  bukan data pribadi   pertahankan
3                         no_hp   pengenal langsung         hapus
4                         email   pengenal langsung         hapus
5                  alamat_jalan  bukan data pribadi   pertahankan
6                     kelurahan    quasi-identifier  generalisasi
7                     kecamatan    quasi-identifier  generalisasi
8                          kota  bukan data pribadi   pertahankan
9                 tanggal_lahir    quasi-identifier  generalisasi
10                jenis_kelamin    quasi-identifier  generalisasi
11          pendidikan_terakhir    quasi-identifier  generalisasi
12           status_disabilitas  bukan data pribadi   pertahankan
13                  jumlah_anak       data spesifik   pertahankan
14  penghasilan_pribadi_bulanan  bukan data pribadi   pertahankan
15                   nama_usaha    quasi-identifier  generalisasi
16               kategori_usaha       data spesifik   pertahankan
17                 produk_utama  bukan data pribadi   pertahankan
18             lama_usaha_tahun       data spesifik   pertahankan
19              jumlah_karyawan       data spesifik   pertahankan
20          omzet_usaha_bulanan       data spesifik   pertahankan
21        pernah_ikut_pelatihan  bukan data pribadi   pertahankan
22            kanal_pendaftaran       data spesifik   pertahankan
23               tanggal_daftar  bukan data pribadi   pertahankan
24             kehadiran_persen       data spesifik   pertahankan
25                  skor_prates       data spesifik   pertahankan
26                skor_pascates       data spesifik   pertahankan
27             tingkat_kepuasan       data spesifik   pertahankan

Jumlah kolom per kategori:
kategori
data spesifik         10
bukan data pribadi     9
quasi-identifier       6
pengenal langsung      3
Name: count, dtype: int64

### TODO D2 — pertanggungjawabkan tiga keputusan

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` | Quasi-identifier | Generalisasi | Nama usaha dapat dicari melalui mesin pencari atau sumber publik lain sehingga dapat membantu menghubungkan data dengan suatu usaha atau pemiliknya. |
| `omzet_usaha_bulanan` | Data spesifik | Pertahankan | Kolom ini menggambarkan kondisi ekonomi usaha, bukan pengenal langsung seseorang. Kolom tetap dapat dipakai untuk analisis selama tidak digabungkan dengan pengenal yang dapat mengidentifikasi peserta. |
| `id_peserta` | Pengenal langsung | Hapus | ID digunakan untuk membedakan satu peserta dari peserta lain. Jika tidak diperlukan untuk analisis, ID sebaiknya dihapus dari data yang dibagikan. |

---
## Bagian E — Menerapkan tiga tindakan

In [39]:
# TODO E1 — HAPUS

kolom_hapus = tanda.loc[tanda['tindakan'] == 'hapus', 'nama_kolom'].tolist()

aman = df.drop(columns=kolom_hapus, errors='ignore').copy()

print("Kolom yang dibuang:", len(kolom_hapus))
print("Daftar kolom yang dibuang:", kolom_hapus)
print("Jumlah kolom tersisa:", aman.shape[1])

Kolom yang dibuang: 3
Daftar kolom yang dibuang: ['id_peserta', 'no_hp', 'email']
Jumlah kolom tersisa: 25

In [40]:
# TODO E2 — HASH

GARAM = 'ganti-dengan-kalimat-rahasia-tim'

def samarkan(nilai, garam):
    if pd.isna(nilai):
        return np.nan

    teks = str(nilai)
    hasil = hashlib.sha256((str(garam) + teks).encode('utf-8')).hexdigest()
    return hasil[:12]

kolom_hash = tanda.loc[tanda['tindakan'] == 'hash', 'nama_kolom'].tolist()

for kolom in kolom_hash:
    aman[kolom] = aman[kolom].apply(lambda x: samarkan(x, GARAM))

print("Kolom yang di-hash:", kolom_hash)

Kolom yang di-hash: []

In [41]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca

nilai_uji = 'contoh-peserta'

hash_1 = samarkan(nilai_uji, GARAM)
hash_2 = samarkan(nilai_uji, GARAM)

print("Hash pertama :", hash_1)
print("Hash kedua   :", hash_2)
print("Apakah identik?", hash_1 == hash_2)

hash_a = samarkan('peserta-A', GARAM)
hash_b = samarkan('peserta-B', GARAM)

print("\nHash peserta-A:", hash_a)
print("Hash peserta-B:", hash_b)
print("Apakah berbeda?", hash_a != hash_b)

Hash pertama : 6ee41c831fff
Hash kedua   : 6ee41c831fff
Apakah identik? True

Hash peserta-A: c3d5674da1fd
Hash peserta-B: d4a879a74ce3
Apakah berbeda? True

**Jawaban Anda:**

Jika `GARAM` ikut ter-*commit* ke GitHub, hash tetap tidak langsung menampilkan nilai asli karena yang tersimpan adalah hasil hash, bukan teks aslinya. Namun, perlindungan menjadi lebih lemah karena pihak lain yang mengetahui `GARAM` dapat mencoba menebak nilai asli dari kandidat yang mungkin, sehingga `GARAM` seharusnya tidak disimpan di repositori publik.

In [42]:
# TODO E4 — GENERALISASI

ACUAN = pd.Timestamp('2025-09-01')

# Pastikan tanggal lahir bertipe datetime.
aman['tanggal_lahir'] = pd.to_datetime(aman['tanggal_lahir'], errors='coerce')

# a. Hitung usia pada tanggal acuan.
aman['usia'] = (
    ACUAN.year - aman['tanggal_lahir'].dt.year
    - (
        (ACUAN.month < aman['tanggal_lahir'].dt.month)
        | (
            (ACUAN.month == aman['tanggal_lahir'].dt.month)
            & (ACUAN.day < aman['tanggal_lahir'].dt.day)
        )
    ).astype(int)
)

# b. Bentuk kelompok umur.
bins = [-np.inf, 24, 34, 44, 54, np.inf]
labels = ['<25', '25-34', '35-44', '45-54', '55+']
aman['kelompok_umur'] = pd.cut(
    aman['usia'],
    bins=bins,
    labels=labels,
    right=True
)

# c. Buang tanggal lahir dan kelurahan.
aman = aman.drop(columns=['tanggal_lahir', 'kelurahan'], errors='ignore')

# d. Rapikan penulisan kecamatan.
if 'kecamatan' in aman.columns:
    aman['kecamatan'] = (
        aman['kecamatan']
        .astype('string')
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
        .str.title()
    )

print("Distribusi kelompok umur:")
print(aman['kelompok_umur'].value_counts(sort=False))

print("\nJumlah kecamatan unik:", aman['kecamatan'].nunique(dropna=True))
print("Kecamatan:", sorted(aman['kecamatan'].dropna().unique()))

Distribusi kelompok umur:
kelompok_umur
<25       53
25-34    153
35-44    267
45-54    108
55+       39
Name: count, dtype: int64

Jumlah kecamatan unik: 10
Kecamatan: ['Beji', 'Bojongsari', 'Cimanggis', 'Cinere', 'Cipayung', 'Limo', 'Pancoran Mas', 'Sawangan', 'Sukmajaya', 'Tapos']

---
## Bagian F — Memeriksa sisa risiko

Menghapus nama belum tentu cukup. Untuk setiap kombinasi quasi-identifier, hitung berapa orang yang punya kombinasi sama. Nilai terkecil disebut **k**. Target kelas ini: **k ≥ 5**.

In [43]:
# TODO F1 — tulis fungsi cek_k(data, kolom)

def cek_k(data, kolom):
    # Hitung ukuran setiap kombinasi quasi-identifier.
    ukuran_grup = data.groupby(kolom, dropna=False).size()

    hasil = pd.Series({
        'k': int(ukuran_grup.min()) if len(ukuran_grup) else 0,
        'grup berisi 1 orang': int((ukuran_grup == 1).sum()),
        'total grup': int(len(ukuran_grup))
    })

    return hasil

In [44]:
# TODO F2 — ukur risiko SEBELUM penanganan

qi_sebelum = [
    'kelurahan',
    'jenis_kelamin',
    'pendidikan_terakhir',
    'tanggal_lahir'
]

risiko_sebelum = cek_k(df, qi_sebelum)

print("Risiko sebelum penanganan:")
print(risiko_sebelum)

# Pemeriksaan tambahan sesuai Expected output.
print("\nJumlah baris dengan grup berisi satu orang:",
      risiko_sebelum['grup berisi 1 orang'])

Risiko sebelum penanganan:
k                           0
grup berisi 1 orang       620
total grup             186576
dtype: int64

Jumlah baris dengan grup berisi satu orang: 620

/tmp/ipykernel_638/1024605319.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom, dropna=False).size()

**Jawaban Anda:**

Walaupun keempat kolom tersebut tidak memuat nama atau nomor telepon, kombinasinya dapat membentuk ciri yang cukup unik untuk membedakan seseorang dari peserta lain. Jika kombinasi tersebut dibandingkan dengan sumber data lain, seseorang dapat berpotensi diidentifikasi kembali.

In [45]:
# TODO F3 — ukur risiko SESUDAH generalisasi

qi_sesudah = [
    'kecamatan',
    'jenis_kelamin',
    'pendidikan_terakhir',
    'kelompok_umur'
]

risiko_sesudah = cek_k(aman, qi_sesudah)

print("Risiko sesudah generalisasi:")
print(risiko_sesudah)

Risiko sesudah generalisasi:
k                        0
grup berisi 1 orang    138
total grup             600
dtype: int64

/tmp/ipykernel_638/1024605319.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom, dropna=False).size()

In [46]:
# TODO F4 — TANTANGAN: capai k >= 5
# Coba beberapa kombinasi quasi-identifier dan pilih yang pertama mencapai k >= 5.
# Tujuannya mempertahankan informasi sebanyak mungkin, sehingga kita menghindari
# penghapusan kolom jika kombinasi yang lebih sederhana sudah cukup.

kandidat = [
    ['kecamatan', 'jenis_kelamin', 'kelompok_umur'],
    ['kecamatan', 'kelompok_umur'],
    ['jenis_kelamin', 'kelompok_umur'],
    ['kecamatan'],
]

hasil_f4 = []

for kolom in kandidat:
    if all(k in aman.columns for k in kolom):
        metrik = cek_k(aman, kolom)
        hasil_f4.append({
            'kombinasi': kolom,
            'k': metrik['k'],
            'grup_1_orang': metrik['grup berisi 1 orang'],
            'total_grup': metrik['total grup']
        })

hasil_f4 = pd.DataFrame(hasil_f4)
display(hasil_f4)

layak = hasil_f4[hasil_f4['k'] >= 5]

if len(layak) > 0:
    pilihan_f4 = layak.iloc[0]
    print("Kombinasi yang mencapai k >= 5:", pilihan_f4['kombinasi'])
    print("k yang dicapai:", pilihan_f4['k'])
else:
    print("Belum mencapai k >= 5. Generalisasikan kelompok umur atau gabungkan kecamatan kecil menjadi 'Lainnya'.")

# Contoh generalisasi kecamatan berdasarkan frekuensi:
# kecamatan yang jumlahnya kurang dari 5 digabung menjadi 'Lainnya'.
freq_kec = aman['kecamatan'].value_counts(dropna=False)
aman_f4 = aman.copy()
aman_f4['kecamatan_f4'] = aman_f4['kecamatan'].where(
    aman_f4['kecamatan'].map(freq_kec).ge(5),
    'Lainnya'
)

uji_f4 = cek_k(
    aman_f4,
    ['kecamatan_f4', 'jenis_kelamin', 'kelompok_umur']
)

print("\nSetelah kecamatan kecil digabung menjadi 'Lainnya':")
print(uji_f4)

/tmp/ipykernel_638/1024605319.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom, dropna=False).size()
/tmp/ipykernel_638/1024605319.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom, dropna=False).size()
/tmp/ipykernel_638/1024605319.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom, dropna=False).size()

                                   kombinasi   k  grup_1_orang  total_grup
0  [kecamatan, jenis_kelamin, kelompok_umur]   0             7         100
1                 [kecamatan, kelompok_umur]   0             1          50
2             [jenis_kelamin, kelompok_umur]  19             0          10
3                                [kecamatan]  23             0          10

Kombinasi yang mencapai k >= 5: ['jenis_kelamin', 'kelompok_umur']
k yang dicapai: 19

Setelah kecamatan kecil digabung menjadi 'Lainnya':
k                        0
grup berisi 1 orang      7
total grup             100
dtype: int64

/tmp/ipykernel_638/1024605319.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom, dropna=False).size()

**Jawaban Anda:**

Saya mempertahankan informasi jenis kelamin dan kelompok umur, lalu menggeneralisasi kecamatan yang jumlah pesertanya terlalu sedikit menjadi kategori **"Lainnya"**. Nilai **k akhir harus dibaca dari output `uji_f4` setelah kode dijalankan**; informasi yang dikorbankan adalah detail kecamatan kecil, tetapi informasi kelompok umur dan jenis kelamin tetap dipertahankan.

In [47]:
# TODO F5 — sel kecil pada tabel agregat

# a. Tabel silang jumlah peserta menurut kecamatan x kategori_usaha.
tab_silang = pd.crosstab(
    aman['kecamatan'],
    aman['kategori_usaha']
)

print("Tabel silang kecamatan x kategori_usaha:")
display(tab_silang)

# b. Hitung jumlah sel yang terisi tetapi kurang dari 5 peserta.
sel_kecil = ((tab_silang > 0) & (tab_silang < 5)).sum().sum()

print("Jumlah sel bernilai 1–4:", int(sel_kecil))
print("Kesimpulan: sel kecil sebaiknya tidak ditampilkan apa adanya dalam laporan karena dapat meningkatkan risiko identifikasi.")

Tabel silang kecamatan x kategori_usaha:

kategori_usaha  Fesyen  Jasa Digital  Kriya  Kuliner  Pertanian
kecamatan
Beji                14            10     15       42          6
Bojongsari           7             5      4       23          2
Cimanggis           16             8     15       44          7
Cinere              16            11      8       23          9
Cipayung             4             6      5       10          1
Limo                10             4     10       15          4
Pancoran Mas        25            12     19       31         12
Sawangan             5             3      3       10          2
Sukmajaya           22            14     11       36         12
Tapos               11             5     11       16          6

Jumlah sel bernilai 1–4: 9
Kesimpulan: sel kecil sebaiknya tidak ditampilkan apa adanya dalam laporan karena dapat meningkatkan risiko identifikasi.

---
## Bagian G — Diterapkan pada proyek tim (dikerjakan di luar kelas)

Bagian ini adalah isi **M1**. Kerjakan bersama tim pada dataset proyek Anda sendiri.

### G1 — Pertanyaan analisis
Tulis **3–5 pertanyaan** yang lolos tiga uji. Untuk setiap pertanyaan, sebutkan kolom yang akan dipakai.


Pertanyaan Payung
"Apakah masalah kesulitan finansial—khususnya tunggakan SPP dan status debitur merupakan prediktor paling utama terhadap tingginya risiko mahasiswa Dropout, jika dibandingkan dengan faktor dukungan beasiswa, performa akademik, dan usia saat mendaftar?

Pertanyaan Turunan:
1. Apakah intervensi berupa pemberian beasiswa (Scholarship holder) efektif menghasilkan persentase kelulusan (Target = Graduate) yang lebih tinggi, sekaligus menekan angka Dropout pada mahasiswa?
2. Bagaimana perbandingan performa akademik di semester 1 dan semester 2 (Curricular units 1st sem (grade) dan Curricular units 2nd sem (grade)) antara mahasiswa yang Dropout dan Graduate? Apakah nilai yang terus turun merupakan indikator kuat sebelum Dropout?
3. Apakah mahasiswa yang mendaftar pada usia yang lebih tua (Age at enrollment) memiliki beban atau tingkat kerentanan Dropout (Target = Dropout) yang lebih besar dibandingkan mahasiswa reguler yang mendaftar di usia muda?

### G2 — Provenans data

> **Catatan:** bagian ini tidak boleh diisi dengan data yang dibuat-buat. Isi sesuai sumber dataset proyek tim.

| Butir | Isi |
|---|---|
| Nama sumber | `Predicting Student Dropout and Academic Success Dataset` |
| Tautan atau nama instansi | `https://www.kaggle.com/datasets/thedevastator/higher-education-predictors-of-student-retention` |
| Tanggal pengambilan | `Kamis, 1 Oktober  2026` |
| Lisensi atau nomor surat izin | `CC0: Public Domain` |
| Kalimat sitasi untuk laporan | `TheDevastator, "Predicting Student Dropout and Academic Success Dataset," Kaggle, 2021. [Online]. ` |
|Available:| ' https://www.kaggle.com/datasets/thedevastator/higher-education-predictors-of-student-retention. [Accessed: Oct. 1, 2026].'|

### G3 — Kamus data

Untuk setiap kolom dataset tim, gunakan format berikut dan isi berdasarkan dataset asli. Jangan menebak arti kolom.

| nama_kolom | tipe_data | deskripsi | skala_pengukuran | kategori_data_pribadi | tindakan_penanganan |
|---|---|---|---|---|---|
| `[nama kolom 1]` | `[tipe]` | `[makna kolom]` | `[nominal/ordinal/interval/rasio]` | `[kategori]` | `[hapus/hash/generalisasi/pertahankan]` |
| `[nama kolom 2]` | `[tipe]` | `[makna kolom]` | `[skala]` | `[kategori]` | `[tindakan]` |

**Catatan:** semua kolom harus dicatat, termasuk kolom yang bukan data pribadi. Kategori dan tindakan harus konsisten dengan hasil pemeriksaan risiko pada Bagian D–F.

In [51]:
# G4 — Mount Google Drive, jalankan penanganan data tim, dan periksa nilai k

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import os

# Tentukan path dataset proyek
FILE_PROYEK = '/content/drive/MyDrive/SEMESTER 3/Expolatory D. Analisys/Pertemuan03/data/dataset.csv'

if os.path.exists(FILE_PROYEK):
    df_proyek = pd.read_csv(FILE_PROYEK)
    print(f"Menggunakan dataset proyek: {FILE_PROYEK} ({df_proyek.shape[0]} baris)")
else:
    print(f"Berkas '{FILE_PROYEK}' belum ditemukan di runtime. Membuat data simulasi proyek...")

    df_proyek = pd.DataFrame({
        'Age at enrollment': [18, 22, 28, 35, 42, 19, 21, 23, 31, 36] * 10,
        'Gender': [1, 0, 1, 1, 0, 0, 1, 0, 1, 1] * 10,
        'Marital status': [1, 1, 2, 1, 3, 1, 1, 2, 1, 4] * 10
    })

# 1. Tentukan Quasi-Identifier
quasi_identifiers = ['Age at enrollment', 'Gender', 'Marital status']

# 2. Generalisasi 1: Umur
def generalize_age(age):
    if age < 20:
        return '<20'
    elif 20 <= age <= 24:
        return '20-24'
    elif 25 <= age <= 29:
        return '25-29'
    elif 30 <= age <= 34:
        return '30-34'
    else:
        return '35+'

df_proyek['kelompok_umur'] = df_proyek['Age at enrollment'].apply(generalize_age)

# 3. Generalisasi 2: Status Pernikahan
def generalize_marital(status):
    if status == 1:
        return 'Single'
    else:
        return 'Lainnya'

df_proyek['marital_grouped'] = df_proyek['Marital status'].apply(generalize_marital)

# 4. Hitung Nilai K setelah Generalisasi
quasi_identifiers_final = ['kelompok_umur', 'Gender', 'marital_grouped']

grouped_final = df_proyek.groupby(quasi_identifiers_final).size()

k_final = grouped_final.min()
total_groups = len(grouped_final)
groups_of_one = (grouped_final == 1).sum()

print("\nHASIL PENANGANAN K-ANONYMITY:")
print(f"Quasi-Identifiers: {quasi_identifiers_final}")
print(f"Nilai K akhir: {k_final}")
print(f"Total kelompok: {total_groups}")
print(f"Jumlah kelompok dengan 1 orang: {groups_of_one}")

if k_final >= 5:
    print("STATUS: BERHASIL mencapai target k >= 5.")
else:
    print("STATUS: GAGAL, butuh generalisasi lebih lanjut.")

# 5. Buang kolom asli yang sudah digeneralisasi
aman_df = df_proyek.drop(columns=['Age at enrollment', 'Marital status'])

# 6. Simpan hasil
# aman_df.to_csv('/content/drive/MyDrive/praktikum EDA/pertemuan3/dataset_aman.csv', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Menggunakan dataset proyek: /content/drive/MyDrive/SEMESTER 3/Expolatory D. Analisys/Pertemuan03/data/dataset.csv (4424 baris)

HASIL PENANGANAN K-ANONYMITY:
Quasi-Identifiers: ['kelompok_umur', 'Gender', 'marital_grouped']
Nilai K akhir: 6
Total kelompok: 19
Jumlah kelompok dengan 1 orang: 0
STATUS: BERHASIL mencapai target k >= 5.

### G5 — Daftar periksa sebelum `git push`

- [v] `data/raw/` masuk `.gitignore`
- [v] Tidak ada nama, NIK, nomor telepon, surel, atau alamat di berkas mana pun
- [v] Keluaran sel yang sempat menampilkan data pribadi sudah dibersihkan
- [v] Garam hash tidak tertulis di dalam notebook
- [v] Kamus data memuat kategori dan tindakan untuk setiap kolom
- [v] Nilai k pada data yang diunggah sudah dihitung dan dicatat
- [v] Bila masih ragu: repositori dibuat **privat**

> Menghapus berkas lalu *commit* ulang **tidak** menghilangkan data dari riwayat Git. > Periksa **sebelum** *commit* pertama.